### ISSUE TITLE
Set up GitHub CI

### ISSUE THREAD

**Issue by redmushie** [OpenShock/ShockOsc#10]
Migrate away from internal CI

**Comment by LucHeart** [comment]
Auto release is also not a thing i would wanna see here, since auto update of shockosc is dependend on tag name and its just better to handle this manually here

**Comment by redmushie** [comment]
> Auto release is also not a thing i would wanna see here, since auto update of shockosc is dependend on tag name and its just better to handle this manually here

I'm not exactly sure what you mean; would it not be fine to just build artifacts and upload tag artifacts on a tag push?

**Comment by LucHeart** [comment]
Implemented with [v2.0.0-rc.1](https://github.com/OpenShock/ShockOsc/tree/v2.0.0-rc.1)
