### ISSUE TITLE
OpenShock branding

### ISSUE THREAD

**Issue by redmushie** [OpenShock/ShockOsc#11]
I see lots of ShockLink branding remaining and I've only looked at the README so far

**Comment by LucHeart** [comment]
What do you mean? The only thing left is in the configuration file, since i dont wanna make a breaking change, maybe at some point ill make a migrator but thats a lot of work.

**Comment by redmushie** [comment]
![Screenshot_2023-10-09-22-59-35-25_3aea4af51f236e4932235fdada7d1643](https://github.com/OpenShock/ShockOsc/assets/82113471/5e71e06a-f0b7-4980-8af4-9ee0c373807f)
![Screenshot_2023-10-09-22-59-41-90_3aea4af51f236e4932235fdada7d1643](https://github.com/OpenShock/ShockOsc/assets/82113471/9588551a-1d76-4561-a02d-e91465ee895b)

**Comment by LucHeart** [comment]
Yes as stated, that is left in on purpose because it would be a breaking change.

**Comment by redmushie** [comment]
![Screenshot_2023-10-09-22-59-30-23_3aea4af51f236e4932235fdada7d1643](https://github.com/OpenShock/ShockOsc/assets/82113471/0a1edbdd-f954-452f-bd48-66fec3eb96b4)

**Comment by redmushie** [comment]
@LucHeart also look at the links on the shields

**Comment by LucHeart** [comment]
fixed with https://github.com/OpenShock/ShockOsc/tree/v2.0.0-rc.1 and before that
