### ISSUE TITLE
Support stateful intensity management

### ISSUE THREAD

**Issue by redmushie** [OpenShock/ShockOsc#13]
- Remember the current intensity (let's say it starts at 5, configurable).
- Add triggers for increasing and decresing said intensity (let's say by +/-5, configurable)
- Add output variable for current intensity
- Add ability to use this stateful intensity configuration when shocking/vibrating/beeping
- Should be compatible with #12

**Comment by LucHeart** [comment]
implemented with [v2.0.0-rc.1](https://github.com/OpenShock/ShockOsc/tree/v2.0.0-rc.1). Remote shockers is on halt due to technical implications.
