### ISSUE TITLE
[Feature Request] Switch between Random and Fixed Duration and Intensity.

### ISSUE THREAD

**Issue by Kyobinoyo** [OpenShock/ShockOsc#27]
I would like:
``ShockOsc/_Config/_All/RandomDuration`` (bool)
``ShockOsc/_Config/_All/RandomIntensity`` (bool)
to be a thing, to toggle between random and fixed duration or/and intensity in-game.
If fixed is on (bool = false) it could just use the minimum as the fixed value.

**Comment by LucHeart** [comment]
Solved with https://github.com/OpenShock/ShockOsc/commit/1dbc7a1949fce676dcdc5bcea16c2027b424d517
