### ISSUE TITLE
Groups show wrong shocker active status when creating a new group

### ISSUE THREAD

**Issue by Kyobinoyo** [OpenShock/ShockOsc#28]
Meaning when you select a group and then create a new group it'll still switch to a "New Group" config but the shocker status is kept the same and is getting update when switching back and forth.

https://github.com/OpenShock/ShockOsc/assets/13241508/5073280d-fee6-4ddf-82d5-07b01fdb4516

**Comment by LucHeart** [comment]
fixed with https://github.com/OpenShock/ShockOsc/commit/1442da7787bd956537b87f5b76c85df9d6d77007
included in next rc (rc.3)
